### ISSUE TITLE
Font?

### ISSUE THREAD

**Issue by ajhalls** [yaronn/blessed-contrib#14]
After installing and running on a CentOS 6.6 server it seems the font may be screwed up as the alignment of everything was off when running on the local terminal. Can this be run on a remote terminal? Would that mean I need to have a specific font installed on the local client?

**Comment by yaronn** [comment]
Hi - what do you mean the local terminal, did you connect via ssh? The font
is determined by the local machine where the terminal window runs on, not
the remote machine where the node process is on.

On Wed, Jan 21, 2015 at 11:23 PM, Alan <notifications@github.com> wrote:

> After installing and running on a CentOS 6.6 server it seems the font may
> be screwed up as the alignment of everything was off when running on the
> local terminal. Can this be run on a remote terminal? Would that mean I
> need to have a specific font installed on the local client?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/blessed-contrib/issues/14>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by ajhalls** [comment]
The server was sitting next to me so I was viewing it on the local machine, and then also tried using it over an SSH connection using SecureCRT as the client. I can select a bunch of different emulation modes, but none looked very good.
![capture](https://cloud.githubusercontent.com/assets/5520815/5846578/e8caa5d4-a181-11e4-87e6-a25094f833f1.PNG)

**Comment by yaronn** [comment]
can you try the simplest example in the blessed readme to see if it works?


On Thu, Jan 22, 2015 at 12:26 AM, Alan <notifications@github.com> wrote:

> The server was sitting next to me so I was viewing it on the local
> machine, and then also tried using it over an SSH connection using
> SecureCRT as the client. I can select a bunch of different emulation modes,
> but none looked very good.
> [image: capture]
> <https://cloud.githubusercontent.com/assets/5520815/5846578/e8caa5d4-a181-11e4-87e6-a25094f833f1.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/blessed-contrib/issues/14#issuecomment-70934663>
> .
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by yaronn** [comment]
https://github.com/chjj/blessed

On Thu, Jan 22, 2015 at 12:28 AM, Yaron Naveh <yaronn01@gmail.com> wrote:

> can you try the simplest example in the blessed readme to see if it works?
>
>
> On Thu, Jan 22, 2015 at 12:26 AM, Alan <notifications@github.com> wrote:
>
>> The server was sitting next to me so I was viewing it on the local
>> machine, and then also tried using it over an SSH connection using
>> SecureCRT as the client. I can select a bunch of different emulation modes,
>> but none looked very good.
>> [image: capture]
>> <https://cloud.githubusercontent.com/assets/5520815/5846578/e8caa5d4-a181-11e4-87e6-a25094f833f1.PNG>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/yaronn/blessed-contrib/issues/14#issuecomment-70934663>
>> .
>>
>
>
>
> --
>
> I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by ajhalls** [comment]
![capture](https://cloud.githubusercontent.com/assets/5520815/5846678/c27761fa-a182-11e4-89ea-005ad8321eb6.PNG)

**Comment by yaronn** [comment]
please try to run this code:


    var blessed = require('blessed')
     , contrib = require('blessed-contrib')
     , screen = blessed.screen()
     , grid = new contrib.grid({rows: 1, cols: 2})

     grid.set(0, 0, contrib.log, {})

     grid.set(0, 1, contrib.table, { keys: true
      , fg: 'green'
      , label: 'Active Processes'
      , columnSpacing: [16, 12, 12] /*or just 16*/})

     grid.applyLayout(screen)

     var table = grid.get(0, 1)

     table.focus()

     table.setData(
     { headers: ['col1', 'col2']
     , data: 
        [ [1, 2] 
        , [3, 4] ]})

     var log = grid.get(0, 0)

     log.log("123")
     log.log("456")

     screen.key(['escape', 'q', 'C-c'], function(ch, key) {
       return process.exit(0);
     });

     screen.render()


in addition please run the simplest example from node-drawille:

https://github.com/madbence/node-drawille

**Comment by ajhalls** [comment]
Thank you so much for your help, using your example I got this:
module.js:340
    throw err;
          ^
Error: Cannot find module 'blessed-contrib'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/devenv/blessed-contrib/examples/simple.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
[root@jetengine examples]# npm install drawille
npm WARN package.json ansi-term@0.0.1 No description
npm WARN package.json ansi-term@0.0.1 No README data
npm WARN package.json map-canvas@0.0.2 No description
npm WARN package.json map-canvas@0.0.2 No repository field.
npm WARN package.json map-canvas@0.0.2 No README data
npm WARN package.json term-canvas@0.0.5 No repository field.
drawille@1.0.0 ../node_modules/drawille

So I ran:
npm install drawille
and tried it's example and got this:

module.js:340
    throw err;
          ^
Error: Cannot find module 'bresenham'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/devenv/blessed-contrib/examples/simple.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by yaronn** [comment]
for my sample install blessed and blessed-contrib
for the other install bresenham
