### ISSUE TITLE
Failed to Install in Arch Linux

### ISSUE THREAD

**Issue by chriscchau** [yaronn/blessed-contrib#142]
Hi 
When I try to install the latest code in Arch Linux. I got the error listed below.  How can I do?

[chris@cccarch blessed-contrib]$ npm install blessed blessed-contrib
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "blessed-contrib" under a package
npm ERR! also called "blessed-contrib". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2018-05-18T07_25_59_051Z-debug.log

Chris

**Comment by rleonard21** [comment]
Looks like the project you are trying to build this is also named `blessed-contrib`. Rename the parent directory to something else?

**Comment by chriscchau** [comment]
Thanks.  I can installed after all.  However I have another problem in running the dashboard.js example.  The errors are listed below.  I am new to Javascript.  Any clue to solve it?  Thanks

/home/chris/blessed-contrib/blessed-contrib/node_modules/gl-matrix/dist/gl-matrix.js:38
})(window, function() {
   ^

ReferenceError: window is not defined
    at Object.<anonymous> (/home/chris/blessed-contrib/blessed-contrib/node_modules/gl-matrix/dist/gl-matrix.js:38:4)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/chris/blessed-contrib/blessed-contrib/node_modules/drawille-canvas-blessed-contrib/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)

**Comment by matthewharwood** [comment]
How do I do this time and time again between so many libs and always get lost with the error message.

**Comment by lirantal** [comment]
@chriscchau how are you trying to run the node example?
Which version of Node.js do you have?
