### ISSUE TITLE
Dependencies outdated?

### ISSUE THREAD

**Issue by annata83** [yaronn/blessed-contrib#186]
Since Blessed isn't been maintain can this be used with neo-blessed?

**Comment by lirantal** [comment]
are there specific deps that need to be updated?

**Comment by annata83** [comment]
Just looking into this and trying to decide where to start and which one to use. This depends on blessed right?

**Comment by daniel-bytes** [comment]
> are there specific deps that need to be updated?

`marked-terminal` seems out of date, I've been running in to the following using the `markdown` module:

```
[ERROR] 09:12:10 TypeError: this.renderer.checkbox is not a function                                                                                                       │
Please report this to https://github.com/markedjs/marked
```

Searching the marked issues, it seems this is actually a `marked-terminal` bug (which is apparently fixed): https://github.com/markedjs/marked/issues/1323#issuecomment-415813602

**Comment by lirantal** [comment]
@daniel-bytes thanks!
looks like latest version is 4, can you confirm it is indeed working well with blessed-contrib and not breaking anything? if so I'll happily release with that

**Comment by daniel-bytes** [comment]
@lirantal thanks!  I cloned the repo and created a file `test.js`:

```
const blessed = require("blessed")
const contrib = require("./index")

const screen = blessed.screen()
const markdown = contrib.markdown()
screen.append(markdown)
markdown.setMarkdown("- [x] Checkbox")
screen.render()
```

running this via `node test.js` gives the following error:
```
TypeError: this.renderer.checkbox is not a function
Please report this to https://github.com/markedjs/marked.
    at Parser.tok (/Users/dbattaglia/code/github/blessed-contrib/node_modules/marked/lib/marked.js:1270:31)
    at Parser.tok (/Users/dbattaglia/code/github/blessed-contrib/node_modules/marked/lib/marked.js:1258:22)
    at Parser.parse (/Users/dbattaglia/code/github/blessed-contrib/node_modules/marked/lib/marked.js:1149:17)
    at Function.Parser.parse (/Users/dbattaglia/code/github/blessed-contrib/node_modules/marked/lib/marked.js:1131:17)
    at marked (/Users/dbattaglia/code/github/blessed-contrib/node_modules/marked/lib/marked.js:1632:19)
    at Markdown.setMarkdown (/Users/dbattaglia/code/github/blessed-contrib/lib/widget/markdown.js:35:19)
    at Object.<anonymous> (/Users/dbattaglia/code/github/blessed-contrib/test.js:8:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

After updating `marked` and `marked-terminal` to latest versions
```
"marked": "^0.8.0",
"marked-terminal": "^4.0.0",
```
I ran the test again and this time I get the appropriate output:
```
    * [X] Checkbox
```

running `node ./examples/dashboard.js` also seemed to work well.

One thing that is odd though is, when I use `npm link` to run my locally cloned copy with updated dependencies against my project I'm working on, I'm getting the following error :
```
No active screen.
    at /Users/dbattaglia/code/github/blessed-contrib/node_modules/blessed/lib/widget.js:41:26
    at Tree.Node (/Users/dbattaglia/code/github/blessed-contrib/node_modules/blessed/lib/widget.js:41:58)
    at Tree.Element (/Users/dbattaglia/code/github/blessed-contrib/node_modules/blessed/lib/widget.js:2128:8)
    at Tree.Box (/Users/dbattaglia/code/github/blessed-contrib/node_modules/blessed/lib/widget.js:4658:11)
    at new Tree (/Users/dbattaglia/code/github/blessed-contrib/lib/widget/tree.js:18:7)
    at Object.Tree (/Users/dbattaglia/code/github/blessed-contrib/lib/widget/tree.js:8:12)
    at Object.<anonymous> (/Users/dbattaglia/code/projects/my-project/app.ts:76:24)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dbattaglia/code/projects/my-project/ui/app.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
where my code at `my-project/app.ts:76:24` looks like
```
  const screen = blessed.screen({ title: "Working On Now" })
  const grid = new contrib.grid({
    rows: 1, 
    cols: 4,
    screen: screen
  })
  
  const tree = contrib.tree({  // <-- Line 76 where error is being thrown
    parent: grid.set(0, 0, 1, 1, blessed.box, { label: 'Working On Now' }),
    fg: 'green',
    keys: ['space']
  })
```
If I run unlinked using `"blessed-contrib": "^4.8.18"` in my `package.json` file it works fine.  Very likely I'm just not using `npm link` correctly though.

**Comment by lirantal** [comment]
Haven't had a chance to look at why that would fail for you. I'll shoot out a PR to upgrade marked-terminal to 4.

**Comment by lirantal** [comment]
BTW 4.8.19 https://www.npmjs.com/package/blessed-contrib published
