### ISSUE TITLE
`4.11.0` leads to `node:process` not found

### ISSUE THREAD

**Issue by schw4rzlicht** [yaronn/blessed-contrib#231]
Hey there,

when upgrading from `4.10.1` to `4.11.0`, we get following error:

```
Error: Cannot find module 'node:process'
Require stack:
- /Users/[...]/node_modules/marked-terminal/index.cjs
- /Users/[...]/node_modules/blessed-contrib/lib/widget/markdown.js
- /Users/[...]/node_modules/blessed-contrib/index.js
- /Users/[...]/src/commands/start/ui/index.ts
- /Users/[...]/src/commands/start/index.ts
- /Users/[...]/src/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/[...]/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/[...]/node_modules/marked-terminal/index.cjs:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/[...]/node_modules/marked-terminal/index.cjs',
    '/Users/[...]/node_modules/blessed-contrib/lib/widget/markdown.js',
    '/Users/[...]/node_modules/blessed-contrib/index.js',
    '/Users/[...]/src/commands/start/ui/index.ts',
    '/Users/[...]/src/commands/start/index.ts',
    '/Users/[...]/src/index.ts'
  ]
}
```

What can we do about it?

**Comment by archoak** [comment]
yes, it does

**Comment by lirantal** [comment]
@schw4rzlicht @oo-long - which node versions are you running on?

**Comment by y4my4my4m** [comment]
@lirantal 14.16.0 for me, same issue

**Comment by lirantal** [comment]
Could you try with the latest Node.js LTS (version 14.19.2) and let me know if it persists?
Might be related to a newer version of marked that's causing it.

**Comment by schw4rzlicht** [comment]
@lirantal indeed node 14.19.3 fixes it for me. Do we want to close this issue here then?

**Comment by lirantal** [comment]
Yes will do. I think we can update the docs about that and leave it at that.
